cursor #e7bdba
cursor_text_color #1a1111

foreground            #f1dedd
background            #1a1111
selection_foreground  #442928
selection_background  #e7bdba
url_color             #ffb3ae

# black
color8   #a08c8b
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green (优化为更舒适清晰的鼠尾草灰绿)
color2   #9ab38d
color10  #b0c9a3

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #ffb3ae
color12 #a39ec4

# magenta
color5   #e2c28c
color13  #ffdea8

# cyan (绑定次要色，利用 fixed_dim 原生实现“调暗”效果，杜绝渲染报错)
color6   #e7bdba
color14  #e7bdba

# white
color15  #e7e7e7
color7   #f0f0f0
