cursor #e4beb4
cursor_text_color #171211

foreground            #ece0dd
background            #171211
selection_foreground  #422b24
selection_background  #e4beb4
url_color             #feb5a1

# black
color8   #9f8d88
color0   #120d0c

# red
color1   #ffb4ab
color9   #690005

# green
color2   #d9c782
color10  #3a3000

# yellow
color3   #e4beb4
color11  #422b24

# blue
color4  #feb5a1
color12 #502316

# magenta
color5   #f5e29b
color13  #282000

# cyan
color6   #e4beb4
color14  #e4beb4

# white
color15  #3f3836
color7   #ece0dd
