cursor #e6bead
cursor_text_color #1a120e

foreground            #f1dfd8
background            #1a120e
selection_foreground  #442a1f
selection_background  #e6bead
url_color             #ffb694

# black
color8   #a08d85
color0   #4c4c4c

# red
color1   #ac8a8c
color9   #c49ea0

# green (优化为更舒适清晰的鼠尾草灰绿)
color2   #9ab38d
color10  #b0c9a3

# yellow
color3   #aca98a
color11  #c4c19e

# blue
color4  #ffb694
color12 #a39ec4

# magenta
color5   #d1c88f
color13  #eee4a9

# cyan (绑定次要色，利用 fixed_dim 原生实现“调暗”效果，杜绝渲染报错)
color6   #e6bead
color14  #e6bead

# white
color15  #e7e7e7
color7   #f0f0f0
