cursor #d8c4a7
cursor_text_color #16130f

foreground            #e9e1da
background            #16130f
selection_foreground  #3b2e1b
selection_background  #d8c4a7
url_color             #ffe0b4

# black
color8   #9a8f81
color0   #100e0a

# red
color1   #ffb4ab
color9   #690005

# green
color2   #deebb0
color10  #2a340a

# yellow
color3   #d8c4a7
color11  #3b2e1b

# blue
color4  #ffe0b4
color12 #432c00

# magenta
color5   #dce9ae
color13  #323c11

# cyan
color6   #d8c4a7
color14  #d8c4a7

# white
color15  #3d3934
color7   #e9e1da
