" XDG Base Directory 规范配置
" 由 ~/.vimrc 转发至此，XDG 变量已在 shell 中设置
set runtimepath^=~/.config/vim
set runtimepath+=~/.config/vim/after

" 备份、交换文件、撤销目录
set backupdir=~/.local/share/vim/backup//
set directory=~/.local/share/vim/swap//
set undodir=~/.local/share/vim/undo//
set viewdir=~/.local/share/vim/views

" 确保目录存在
for s:dir in [
      \ expand('~/.local/share/vim/backup'),
      \ expand('~/.local/share/vim/swap'),
      \ expand('~/.local/share/vim/undo'),
      \ expand('~/.local/share/vim/views')]
  if !isdirectory(s:dir)
    call mkdir(s:dir, 'p')
  endif
endfor

" ========== 基础设置 ==========
set nocompatible
filetype plugin indent on
syntax on

" 编码
set encoding=utf-8
set fileencodings=utf-8,gbk,gb2312,cp936,ucs-bom,latin1

" 行号
set number
set relativenumber

" 缩进
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent
set smartindent

" 搜索
set hlsearch
set incsearch
set ignorecase
set smartcase

" 界面
set laststatus=2
set ruler
set showcmd
set wildmenu
set cursorline
set signcolumn=yes
set scrolloff=5
set sidescrolloff=5

" 行为
set hidden
set backspace=indent,eol,start
set whichwrap+=<,>,h,l
set clipboard=unnamedplus
set mouse=a
set timeoutlen=500
set updatetime=300
set undofile
set autoread
set confirm

" 折叠
set foldmethod=marker
set foldlevelstart=99

" 不生成备份和交换文件（已集中管理）
set writebackup
set backupcopy=yes

" 分屏
set splitbelow
set splitright

" 补全
set completeopt=menuone,noselect

" ========== 键位映射 ==========
let mapleader = ' '

" 快速保存退出
nnoremap <leader>w :write<CR>
nnoremap <leader>q :quit<CR>

" 窗口导航
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" 清除搜索高亮
nnoremap <leader>h :nohlsearch<CR>

" 缓冲区切换
nnoremap <leader>n :bnext<CR>
nnoremap <leader>p :bprev<CR>

" ========== 自动命令 ==========
augroup auto_settings
  autocmd!
  " 保存时自动去除行尾空白
  autocmd BufWritePre * if search('\s\+$', 'nw') | %s/\s\+$//e | endif
  " 打开文件时恢复上次光标位置
  autocmd BufReadPost *
    \ if line("'\"") >= 1 && line("'\"") <= line('$') |
    \   execute 'normal! g`"' |
    \ endif
augroup END
