# KDE session: use the KDE-generated Fcitx5 Plasma theme and follow KDE mode.
Vertical Candidate List=False
WheelForPaging=True
Font="LXGW WenKai Mono Medium 11"
MenuFont="LXGW WenKai Mono Medium 10"
TrayFont="LXGW WenKai Mono Bold 10"
TrayOutlineColor=#000000
TrayTextColor=#ffffff
PreferTextIcon=False
ShowLayoutNameInIcon=True
UseInputMethodLanguageToDisplayText=True
Theme=plasma
DarkTheme=plasma
UseDarkTheme=True
UseAccentColor=True
PerScreenDPI=False
ForceWaylandDPI=0
EnableFractionalScale=True
