# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e2e2e6"

# Title color for boxes
theme[title]="#b7d9ff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#b8c8dc"

# Background color of selected item in processes box
theme[selected_bg]="#b7d9ff"

# Foreground color of selected item in processes box
theme[selected_fg]="#003354"

# Color of inactive/disabled text
theme[inactive_fg]="#c2c7cf"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#f5c6fe"

# Cpu box outline color
theme[cpu_box]="#8c9199"

# Memory/disks box outline color
theme[mem_box]="#8c9199"

# Net up/down box outline color
theme[net_box]="#8c9199"

# Processes box outline color
theme[proc_box]="#8c9199"

# Box divider line and small boxes line color
theme[div_line]="#42474e"

# Temperature graph colors
theme[temp_start]="#b8c8dc"
theme[temp_mid]="#b7d9ff"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#b8c8dc"
theme[cpu_mid]="#b7d9ff"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#b8c8dc"
theme[free_mid]=""
theme[free_end]="#394859"

# Mem/Disk cached meter
theme[cached_start]="#f5c6fe"
theme[cached_mid]=""
theme[cached_end]="#d8abe1"

# Mem/Disk available meter
theme[available_start]="#b7d9ff"
theme[available_mid]=""
theme[available_end]="#93beeb"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#b8c8dc"
theme[download_mid]="#b7d9ff"
theme[download_end]="#f5c6fe"

# Upload graph colors
theme[upload_start]="#b8c8dc"
theme[upload_mid]="#b7d9ff"
theme[upload_end]="#f5c6fe"
