# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#ece0dd"

# Title color for boxes
theme[title]="#feb5a1"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#e4beb4"

# Background color of selected item in processes box
theme[selected_bg]="#feb5a1"

# Foreground color of selected item in processes box
theme[selected_fg]="#502316"

# Color of inactive/disabled text
theme[inactive_fg]="#d7c2bc"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#d9c782"

# Cpu box outline color
theme[cpu_box]="#9f8d88"

# Memory/disks box outline color
theme[mem_box]="#9f8d88"

# Net up/down box outline color
theme[net_box]="#9f8d88"

# Processes box outline color
theme[proc_box]="#9f8d88"

# Box divider line and small boxes line color
theme[div_line]="#52433f"

# Temperature graph colors
theme[temp_start]="#e4beb4"
theme[temp_mid]="#feb5a1"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#e4beb4"
theme[cpu_mid]="#feb5a1"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#e4beb4"
theme[free_mid]=""
theme[free_end]="#5b4039"

# Mem/Disk cached meter
theme[cached_start]="#d9c782"
theme[cached_mid]=""
theme[cached_end]="#bcab69"

# Mem/Disk available meter
theme[available_start]="#feb5a1"
theme[available_mid]=""
theme[available_end]="#6f3c2d"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#e4beb4"
theme[download_mid]="#feb5a1"
theme[download_end]="#d9c782"

# Upload graph colors
theme[upload_start]="#e4beb4"
theme[upload_mid]="#feb5a1"
theme[upload_end]="#d9c782"
