# Matugen template for btop


# Colors should be in 6 or 2 character hexadecimal or single spaced rgb decimal: "#RRGGBB", "#BW" or "0-255 0-255 0-255"
# example for white: "#ffffff", "#ff" or "255 255 255".

# All graphs and meters can be gradients
# For single color graphs leave "mid" and "end" variable empty.
# Use "start" and "end" variables for two color gradient
# Use "start", "mid" and "end" for three color gradient

# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=""

# Main text color
theme[main_fg]="#e9e1da"

# Title color for boxes
theme[title]="#ffe0b4"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#d8c4a7"

# Background color of selected item in processes box
theme[selected_bg]="#ffe0b4"

# Foreground color of selected item in processes box
theme[selected_fg]="#432c00"

# Color of inactive/disabled text
theme[inactive_fg]="#d1c5b6"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#deebb0"

# Cpu box outline color
theme[cpu_box]="#9a8f81"

# Memory/disks box outline color
theme[mem_box]="#9a8f81"

# Net up/down box outline color
theme[net_box]="#9a8f81"

# Processes box outline color
theme[proc_box]="#9a8f81"

# Box divider line and small boxes line color
theme[div_line]="#4e463a"

# Temperature graph colors
theme[temp_start]="#d8c4a7"
theme[temp_mid]="#ffe0b4"
theme[temp_end]="#ffb4ab"

# CPU graph colors
theme[cpu_start]="#d8c4a7"
theme[cpu_mid]="#ffe0b4"
theme[cpu_end]="#ffb4ab"

# Mem/Disk free meter
theme[free_start]="#d8c4a7"
theme[free_mid]=""
theme[free_end]="#53452f"

# Mem/Disk cached meter
theme[cached_start]="#deebb0"
theme[cached_mid]=""
theme[cached_end]="#c2cf96"

# Mem/Disk available meter
theme[available_start]="#ffe0b4"
theme[available_mid]=""
theme[available_end]="#e9c388"

# Mem/Disk used meter
theme[used_start]="#ffb4ab"
theme[used_mid]=""
theme[used_end]="#93000a"

# Download graph colors
theme[download_start]="#d8c4a7"
theme[download_mid]="#ffe0b4"
theme[download_end]="#deebb0"

# Upload graph colors
theme[upload_start]="#d8c4a7"
theme[upload_mid]="#ffe0b4"
theme[upload_end]="#deebb0"
