-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#16130f', -- 背景
  base01 = '#100e0a', --较浅的背景色
  base02 = '#1e1b17',
  base03 = '#ffe0b4', -- 键盘字符，匹配大括号
  base04 = '#d1c5b6',
  base05 = '#ffe0b4', -- 括号，运算符
  base06 = '#34302b',
  base07 = '#3d3934',

  base08 = '#deebb0',-- 变量名
  base09 = '#f5dfc2', -- 整数、布尔值 (True/False)。
  base0A = '#d8c4a7', --类名 (Class)、搜索匹配到的背景
  base0B = '#e7c186', -- 字符串
  base0C = '#c0cc94',
  base0D = '#e9c388', -- 函数名
  base0E = '#d8c4a7', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e9e1da', -- 选中文字背景
  fg = '#16130f', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#9a8f81', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#deebb0',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#d8c4a7',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#765a29',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#221f1b', --底边
  fg = '#ffe0b4',
})
