-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#1a120e', -- 背景
  base01 = '#140c09', --较浅的背景色
  base02 = '#221a16',
  base03 = '#ffb694', -- 键盘字符，匹配大括号
  base04 = '#d7c2ba',
  base05 = '#ffb694', -- 括号，运算符
  base06 = '#382e2a',
  base07 = '#423732',

  base08 = '#d1c88f',-- 变量名
  base09 = '#ffdbcc', -- 整数、布尔值 (True/False)。
  base0A = '#e6bead', --类名 (Class)、搜索匹配到的背景
  base0B = '#ffb694', -- 字符串
  base0C = '#d1c88f',
  base0D = '#713719', -- 函数名
  base0E = '#e6bead', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#f1dfd8', -- 选中文字背景
  fg = '#1a120e', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#a08d85', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d1c88f',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#e6bead',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#8e4d2e',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#271e1a', --底边
  fg = '#ffb694',
})
