-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#111416', -- 背景
  base01 = '#0c0e11', --较浅的背景色
  base02 = '#1a1c1e',
  base03 = '#b7d9ff', -- 键盘字符，匹配大括号
  base04 = '#c2c7cf',
  base05 = '#b7d9ff', -- 括号，运算符
  base06 = '#2f3033',
  base07 = '#37393c',

  base08 = '#f5c6fe',-- 变量名
  base09 = '#d4e4f9', -- 整数、布尔值 (True/False)。
  base0A = '#b8c8dc', --类名 (Class)、搜索匹配到的背景
  base0B = '#9fcbf8', -- 字符串
  base0C = '#e5b7ee',
  base0D = '#93beeb', -- 函数名
  base0E = '#b8c8dc', -- 关键词 (if, else, return, import)。
  base0F = '#ffb4ab',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#e2e2e6', -- 选中文字背景
  fg = '#111416', -- 选中文字颜色
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#8c9199', -- 注释
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#f5c6fe',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b8c8dc',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#35628a',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#1e2023', --底边
  fg = '#b7d9ff',
})
